spring.profiles:
  include:
    -aws
  active: local # 기본 환경 선택

spring:
  profiles:
    group:
      local:
      real-db:

# local 환경
---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    data: classpath:data-h2.sql # 시작할때 실행시킬 script
  h2:
    console:
      enabled: true

# 운영 환경
---
spring:
  config:
    activate:
      on-profile: real-db
  include: aws